### ISSUE TITLE
Remove appendSession Usage

### ISSUE THREAD

**Issue by shyim** [wirecard/shopware-wcp#73]
https://github.com/wirecard/shopware-wcp/blob/ace25542b29cf5b70505dd4b08d8a4a6a20a8cdb/Frontend/WirecardCheckoutPage/Controllers/Frontend/WirecardCheckoutPage.php#L82
appendSession should be not used anymore. This functionality has been removed with 5.5.7

**Comment by serucee** [comment]
Hello @shyim ,

sorry for the late response. We will look into the described issue and inform you as soon as possible.

Kind regards,
Wirecard Shop Systems Team

**Comment by miha1** [comment]
Hello @shyim 
The issue is fixed in release 1.6.3
